
name: LaTeX PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeXLive (basic) + latexmk + biber + inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends             texlive-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended             texlive-science texlive-lang-european             latexmk biber inkscape

      - name: Build PDF (TikZ + SVG, with biber)
        working-directory: src
        run: |
          latexmk -pdf -interaction=nonstopmode -shell-escape JUMP_whitepaper.tex
          latexmk -pdf -interaction=nonstopmode -shell-escape JUMP_whitepaper.tex
          # copy output to repository outputs/ for artifact upload
          mkdir -p ../outputs
          cp JUMP_whitepaper.pdf ../outputs/JUMP_whitepaper.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: JUMP_whitepaper_PDF
          path: outputs/JUMP_whitepaper.pdf
